database:
  sqlite_file: db.sqlite
backend:
  base_url: https://cn.chat.nfzs.live/api
  ws_url: wss://cn.chat.nfzs.live/api/ws/ws

youdao:
  app_key: ''
  app_secret: ''
tencent:
  api_key: ''
  secret_id: ''
  map_key: ''
